# hostname (and path) to the root eg. http://spf13.com/
baseURL = "https://yusufyogia.co.vu"
 
# Site title
title = "Yusuf Yogi Antoro Makfud"

# Copyright
copyright = "Copyright (c) 2014-2019 Yusuf Yogi Antoro Makfud. Powered with Hugo"

# Language
languageCode = "en-EN"

# Metadata format
# "yaml", "toml", "json"
metaDataFormat = "toml"

# Theme to use (located in /themes/THEMENAME/)
theme = "hyde-y"

# Pagination
paginate = 5
paginatePath = "page"

# Enable Disqus integration
disqusShortname = "your_disqus_shortname"
[menu.main]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
  

[permalinks]
    post = "/:year/:month/:day/:slug/"
    code = "/:slug/"

[taxonomies]
    tag = "tags"
    topic = "topics"

[author]
    name = "Yusuf Yogi Antoro Makfud"
    email = "yusufixdduapuluhsembilan@gmail.com"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # You can use markdown here.
    brand = "Homepage"
    topline = "of Yusuf Yogi Antoro M"
    footline = ""
 
    # Sidebar position
    # false, true, "left", "right"
    sidebar = "left"

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Home".
    home = "Home"
  	about = "About"
    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "default"

    # Google Analytics.
    googleAnalytics = "Your Google Analytics tracking code"

    # Sidebar social links.
    github = "yusufyogia" # Your Github profile ID
    bitbucket = "" # Your Bitbucket profile ID
    linkedin = "yusufyogia" # Your LinkedIn profile ID (from public URL)
    googleplus = "" # Your Google+ profile ID
    facebook = "" # Your Facebook profile ID
    twitter = "" # Your Twitter profile ID
    youtube = ""  # Your Youtube channel ID
    flattr = ""  # populate with your flattr uid
    flickr = "" # Your Flickr profile ID
    vimeo = "" # Your Vimeo profile ID

    # Sidebar RSS link: will only show up if there is a RSS feed
    # associated with the current page
    rss = true

[blackfriday]
    angledQuotes = true
    fractions = false
    hrefTargetBlank = false
    latexDashes = true
    plainIdAnchors = true
    extensions = []
    extensionmask = []